// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var roomNo, temp;
    roomNo = 1;
    temp = 20;
    return $('#submit').click(function() {
      return $.ajax({
        url: 'http://localhost:3000/setTemp.json',
        data: {
          data: [roomNo, temp]
        },
        type: 'post'
      });
    });
  });

}).call(this);
