// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    var roomNo, run, temp;
    roomNo = 1;
    temp = 20;
    run = function() {
      $.ajax({
        url: 'http://localhost:3000/logTemp.json',
        data: {
          data: [roomNo, temp]
        },
        type: 'post'
      });
      if (roomNo >= 4) {
        roomNo = 1;
      } else {
        roomNo += 1;
      }
      temp += 1;
      return console.log("run was called!");
    };
    setInterval(run, 3000);
    return $('#submit').click(function() {
      return $.ajax({
        url: 'http://localhost:3000/setTemp.json',
        data: {
          data: [roomNo, temp]
        },
        type: 'post'
      });
    });
  });

}).call(this);
