// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var roomNo, run, temp;
    roomNo = 1;
    temp = 20;
    run = function() {
      $.ajax({
        url: 'http://localhost:3000/logTemp.json',
        data: {
          data: [roomNo, temp]
        },
        type: 'post'
      });
      if (roomNo >= 4) {
        roomNo = 1;
      } else {
        roomNo += 1;
      }
      temp += 1;
      return console.log("run was called!");
    };
    setInterval(run, 3000);
    return $('#submit').click(function() {
      roomNo = $('#roomNo option:selected').text();
      temp = $('#value').val();
      return $.ajax({
        url: 'http://localhost:3000/getTemp.json',
        data: {
          data: "room" + roomNo
        },
        type: 'get',
        dataType: 'json',
        timeout: 3000,
        success: function(json) {
          return alert(JSON.stringify(json));
        },
        error: function(error) {
          return alert(JSON.stringify("" + error.status + " " + error.statusText));
        }
      });
    });
  });

}).call(this);
